apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-demo
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - project
    labelSelectors:
      'app': 'kafka-producer'
  scheduler:
    cron: '@every 10s'