# docker-compose up -d --build
version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: 'my-mongo-container'
    environment:
      - MONGO_INITDB_DATABASE=mydb
      - MONGO_NON_ROOT_USERNAME=
      - MONGO_NON_ROOT_PASSWORD=
      - MONGO_INITDB_ROOT_USERNAME=rootdev
      - MONGO_INITDB_ROOT_PASSWORD=rootdev
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - '27017-27019:27017-27019'

  redis:
    image: 'redis'
    container_name: 'my-redis-container'
    # command: redis-server --requirepass rootdev
    ports:
      - '6379:6379'