apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-client-service
  namespace: project
data:
 nginx.conf: |-
    events {}
    http {
        server {
          listen 80;
            location / {
                return 200 "V2\n";
            }
        }
    }